[package]
name = "raw_sync"
version = "0.1.0"
authors = ["elast0ny <elast0ny00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.*"
rand = "0.*"
log = "0.4"

[dev-dependencies]
env_logger = "0.7"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "winerror", "ntdef", "synchapi", "handleapi"]}